<script setup>
import { onMounted, ref, watch } from 'vue';
import ApexCharts from 'apexcharts';
import { useUsageService } from '@/services/usageService';

const { getUsageReportRequest } = useUsageService()

const showDropdown = ref(false);

const toggleDropdown = () => {
  (showDropdown.value)
    ? showDropdown.value = false
    : showDropdown.value = true
}

const days = ref(null);
const chartOptions = ref(null);
const chart = ref(null);

const dates = ref({
  start: null,
  end: null
})

const updateOptions = (counts, names) => {
  chartOptions.value = {
    series: counts,
    chart: {
      height: 420,
      width: "100%",
      type: "pie",
    },
    stroke: {
      colors: ["white"],
      lineCap: "",
    },
    plotOptions: {
      pie: {
        labels: {
          show: true,
        },
        size: "100%",
        dataLabels: {
          offset: -25
        }
      },
    },
    labels: names,
    dataLabels: {
      enabled: true,
      style: {
        fontFamily: "Inter, sans-serif",
      },
    },
    legend: {
      position: "bottom",
      fontFamily: "Inter, sans-serif",
      labels: {
        colors: ["#aaa", "#aaa"],
      }
    },
    yaxis: {
      labels: {
        formatter: function (value) {
          return value + " minutes"
        },
      },
    },
    xaxis: {
      labels: {
        formatter: function (value) {
          return value  + "%"
        },
      },
      axisTicks: {
        show: false,
      },
      axisBorder: {
        show: false,
      },
    },
  }
}

onMounted( async () => {

  days.value = parseInt(sessionStorage.getItem('pie-usage-last-days')) || 7;

  const { data } = await getUsageReportRequest({ days: days.value });

  dates.value.start = data.start_date;
  dates.value.end = data.end_date

  updateOptions([
    data.chatbot,
    data.travel
  ], Object.keys(data).slice(0, 2));

  if (document.getElementById("pie-chart") && typeof ApexCharts !== 'undefined') {
    chart.value = new ApexCharts(document.getElementById("pie-chart"), chartOptions.value);
    chart.value.render();
  }
})

watch(days, async (days) => {
  sessionStorage.setItem('pie-usage-last-days', days);

  const { data } = await getUsageReportRequest({ days: days });

  dates.value.start = data.start_date;
  dates.value.end = data.end_date

  updateOptions([
    data.chatbot,
    data.travel
  ], Object.keys(data).slice(0, 2));

  chart.value.updateOptions(chartOptions.value);
})

</script>

<template>
  <div>
    <!-- circle -->

    <div class="max-w-sm w-full bg-white rounded-lg shadow dark:bg-gray-800 p-4 md:p-6">

      <div class="flex justify-between items-start w-full">
          <div class="flex-col items-center">
            <div class="flex items-center mb-1">
                <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white me-1">Application Usage</h5>
                <div data-popover id="chart-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                    <div class="p-3 space-y-2">
                        <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                        <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                        <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                        <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                        <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                  </svg></a>
                  </div>
                <div data-popper-arrow></div>
            </div>
          </div>

          <div id="dateRangeDropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-80 lg:w-96 dark:bg-gray-700 dark:divide-gray-600">
              <div class="p-3" aria-labelledby="dateRangeButton">
                <div date-rangepicker datepicker-autohide class="flex items-center">
                    <div class="relative">
                      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                          </svg>
                      </div>
                      <input name="start" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Start date">
                    </div>
                    <span class="mx-2 text-gray-500 dark:text-gray-400">to</span>
                    <div class="relative">
                      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                          </svg>
                      </div>
                      <input name="end" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="End date">
                  </div>
                </div>
              </div>
          </div>
        </div>
        
      </div>

      <!-- Line Chart -->
      <div class="py-6" id="pie-chart"></div>

      <div class="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between">
        <div class="flex justify-between items-center pt-5 relative">
          <!-- Button -->
          <button
            @click="toggleDropdown"
            id="dropdownDefaultButton"
            data-dropdown-toggle="lastDaysdropdown"
            data-dropdown-placement="bottom"
            class="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white"
            type="button">
            Last {{ days }} days
            <svg class="w-2.5 m-2.5 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg>
          </button>
          <div
            :class="[showDropdown ? 'opacity-100' : 'opacity-0 hidden']"
            id="lastDaysdropdown" 
            class="z-10 bg-white divide-y absolute bottom-12 -left-8 divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
              <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
                <li>
                  <button @click="days = 7" class="w-full text-start block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 7 days</button>
                </li>
                <li>
                  <button @click="days = 30" class="w-full text-start block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 30 days</button>
                </li>
                <li>
                  <button @click="days = 90" class="w-full text-start block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 90 days</button>
                </li>
              </ul>
          </div>

          <div class="inline-flex items-center text-blue-700 dark:text-blue-600 font-medium hover:underline">
            {{ dates.start }} - {{ dates.end }}
          </div>
        </div>
      </div>
    </div>
  <!-- circle end -->
  </div>
</template>